//ACTIONS FOR POST
export const GET_ALL_POST = 'GET_ALL_POST';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID'


//ACTIONS FOR COMMENT
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT';
export const CREATE_NEW_COMMENT = 'CREATE_NEW_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT_BY_ID = 'DELETE_COMMENT_BY_ID'

//ACTIONS FOR TODO
export const GET_ALL_TODO = 'GET_ALL_TODO';
export const CREATE_NEW_TODO = 'CREATE_NEW_TODO';
export const UPDATE_TODO = 'UPDATE_TODO';
export const DELETE_TODO_BY_ID = 'DELETE_TODO_BY_ID'


// ACTION FOR API CALL
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR'